name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate trophy.svg
        uses: lowlighter/metrics@latest
        with:
          filename: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_trophies: yes

      - name: Push trophy.svg to trophy-output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: trophy-output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
